```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.model_zoo import load_url


class AnomalyClassifier(nn.Module):
    """
    Anomaly classification model supporting multi-class prediction with probability distributions.
    Supports GPU acceleration and model versioning with metadata.
    """

    MODEL_METADATA = {
        'name': 'AnomalyClassifier',
        'version': '1.0.0',
        'description': 'Deep learning model for multi-class anomaly classification',
        'author': 'AutoGenerated',
        'input_features_dim': 512,
        'num_classes': 5  # default number of supported anomaly classes
    }

    def __init__(self, input_dim=512, num_classes=5):
        super(AnomalyClassifier, self).__init__()
        self.input_dim = input_dim
        self.num_classes = num_classes

        self.feature_extractor = nn.Sequential(
            nn.Linear(self.input_dim, 1024),
            nn.ReLU(inplace=True),
            nn.Dropout(0.3),
            nn.Linear(1024, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.3),
        )
        self.classifier = nn.Linear(512, self.num_classes)

        self._metadata = dict(self.MODEL_METADATA)
        self._metadata['num_classes'] = self.num_classes
        self._metadata['input_features_dim'] = self.input_dim

    def forward(self, x):
        x = self.feature_extractor(x)
        logits = self.classifier(x)
        return logits

    def classify(self, features, device=None):
        """
        Classify anomaly types given image features.

        Args:
            features (torch.Tensor or numpy.ndarray): Input features tensor of shape (N, input_dim).
            device (str or torch.device, optional): Device to run inference on. Defaults to GPU if available.

        Returns:
            dict: {
                'labels': list of predicted anomaly class indices,
                'probabilities': tensor of softmax probabilities (N, num_classes)
            }
        """
        if not torch.is_tensor(features):
            features = torch.tensor(features, dtype=torch.float32)

        if device is None:
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.to(device)
        features = features.to(device)

        self.eval()
        with torch.no_grad():
            logits = self.forward(features)
            probs = F.softmax(logits, dim=1)
            labels = torch.argmax(probs, dim=1)

        return {
            'labels': labels.cpu().tolist(),
            'probabilities': probs.cpu()
        }

    def load_model(self, path_or_url, map_location=None):
        """
        Load trained weights from a local path or a URL.

        Args:
            path_or_url (str): Path or URL to the checkpoint file.
            map_location (str or torch.device, optional): Device mapping for loading model weights.
                Defaults to None (auto-select).
        """
        if map_location is None:
            map_location = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        checkpoint = torch.load(path_or_url, map_location=map_location)

        if isinstance(checkpoint, dict):
            state_dict = checkpoint.get('state_dict', checkpoint)
            metadata = checkpoint.get('metadata', {})
            # Update model metadata if available in checkpoint
            self._metadata.update(metadata)
        else:
            state_dict = checkpoint

        self.load_state_dict(state_dict)
        self.to(map_location)
        self.eval()

    @property
    def metadata(self):
        return self._metadata

    def get_version(self):
        return self._metadata.get('version', 'unknown')

    def to_device(self, device=None):
        if device is None:
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.to(device)
        return device
```